#! /usr/bin/env python

def f(x,y):
    return 3*x**3 + 4*y**3 - 10*x*y**2 - 2*x**2 + 0.5*y**2 + 2*x + 9*y - 2*x*y + 1


NRUNS = 100
OUTDIR = "out"

import sys
if len(sys.argv) > 1:
    NRUNS = int(sys.argv[1])
if len(sys.argv) > 2:
    OUTDIR = sys.argv[2]

import os
os.makedirs(OUTDIR)
for i in xrange(NRUNS):
    rundir = os.path.join(OUTDIR, "{0:03d}".format(i))
    os.makedirs(rundir)

    import random
    x = random.uniform(0, 20)
    y = random.uniform(0, 20)

    with open(os.path.join(rundir, "params.dat"), "w") as pf:
        pf.write("x  %e\n" % x)
        pf.write("y  %e\n" % y)

    val = f(x,y)

    import yoda
    s = yoda.Scatter2D("/foo") #< TODO: should be able to use Scatter1D
    s.addPoint(0,val)
    yoda.write(s, os.path.join(rundir, "data.yoda"))
