#! /usr/bin/env python

import numpy as np

def f(x,y):
    return 3*x**3  - 10*x*y**2 - 2*x**2 + 5*y**2
def fprime(x,y):
    return 9*x**2  - 10*(y**2 + 2*x*y) - 4*x + 10*y

A = np.linspace(0, 10, 11)
M_X, M_Y = np.meshgrid(A, A)
M_Z = np.empty(M_X.shape)
M_dZ = np.empty(M_X.shape)

P, Y, dY = [], [], []
for i in xrange(M_X.shape[0]):
    for j in xrange(M_X.shape[1]):
        P.append([i,j])
        Y.append(f(i,j))
        dY.append(fprime(i,j))

import professor2 as prof
import sys
order = int(sys.argv[1]) if len(sys.argv) > 1 else 3
ipol = prof.Ipol(P, Y, order)

for i in xrange(M_X.shape[0]):
    for j in xrange(M_X.shape[1]):
        M_Z[i,j]  = ipol.val([M_X[i,j], M_Y[i,j]])
        M_dZ[i,j] = ipol.der([M_X[i,j], M_Y[i,j]])

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
X1, Y1 = zip(*P)
Z1 = Y
ax.scatter(X1, Y1,  Y, c="b")
ax.scatter(X1, Y1, dY, c="r")
ax.plot_wireframe(M_X, M_Y, M_Z, rstride=1, cstride=1)
ax.plot_wireframe(M_X, M_Y, M_dZ, rstride=1, cstride=1, color="red")
plt.show()

