#!/usr/bin/env python

import numpy as np
def f(x):
    return 3*x**3 + 2*x +1
A = np.linspace(0, 10, 20)
X = np.array([[a] for a in A])
Y = f(A)

from professor2 import ProfMaster
pm = ProfMaster(X)
pm.addIpol("f1", Y, 1)
pm.addIpol("f2", Y, 2)
pm.addIpol("f3", Y, 3)
pm.addIpol("f4", Y, 4)
pm.addIpol("f5", Y, 5)
pm.addIpol("f6", Y, 6)

Z1 = [pm.value("f1", x) for x in X]
Z2 = [pm.value("f2", x) for x in X]
Z3 = [pm.value("f3", x) for x in X]
Z4 = [pm.value("f4", x) for x in X]
Z5 = [pm.value("f5", x) for x in X]
Z6 = [pm.value("f6", x) for x in X]

import pylab as pl
pl.plot(A, Y, "ro", label="Anchors")
pl.plot(X, Z1, "--", label="Ipol 1")
pl.plot(X, Z2, "--", label="Ipol 2")
pl.plot(X, Z3, "--", label="Ipol 3")
pl.plot(X, Z4, "--", label="Ipol 4")
pl.plot(X, Z5, "--", label="Ipol 5")
pl.plot(X, Z6, "--", label="Ipol 6")
pl.legend(loc="best")
pl.show()
