#!/usr/bin/env python

import numpy as np
def f(x):
    return 3*x**3 + 2*x +1
# TODO: also try a non-polynomial function, e.g. sin

A = np.linspace(0, 10, 20)
Y = f(A)

import professor2 as prof
X = np.array([[a] for a in A])
ipols = [prof.Ipol(X, Y, i, "order%i" % i) for i in xrange(0,7)]
Z = [[i.value(x) for x in X] for i in ipols]

import pylab
pylab.plot(A, Y, "ro", label="Anchors")
for num, z in enumerate(Z):
    pylab.plot(X, z, "-", label="Ipol order %i" % (num+1))
pylab.legend(loc=2)
pylab.show()
